<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="WIN-CNIQ7GSBK1T" failures="2" tests="4" name="Test" time="63.694" errors="0" timestamp="2024-08-09T21:44:59 IST">
  <testcase classname="com.vig.practice.testcases.TC002_Login" name="accountLogin" time="8.749"/>
  <testcase classname="com.vig.practice.testcases.TC003_LoginDataDrivenTest" name="datadriventest" time="21.91">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.vig.practice.testcases.TC003_LoginDataDrivenTest.datadriventest(TC003_LoginDataDrivenTest.java:29)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- datadriventest -->
  <testcase classname="com.vig.practice.testcases.TC003_LoginDataDrivenTest" name="datadriventest" time="22.707">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.vig.practice.testcases.TC003_LoginDataDrivenTest.datadriventest(TC003_LoginDataDrivenTest.java:29)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- datadriventest -->
  <testcase classname="com.vig.practice.testcases.TC003_LoginDataDrivenTest" name="datadriventest" time="5.81"/>
</testsuite> <!-- Test -->
